name: stayontarget
favicon: null
layout_spectrum: 0.6639470455702394
typography_spectrum: 0.3088914731051773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00a6de'
    - '#4d4e4c'
    - '#9cdcf1'
    - '#b2b3b2'
  brandStrength: 0.4375
  lightness: 0.35259006451815367
  saturation: 0.8988527802284807
  rhythmicContrast: 0.7749830661341548
purpose: []
